version: '3'

services:
  finalquiz:
    build: .
    image: finalquiz:1.0
    container_name: finalquiz
    ports:
      - '8080:8080'
    depends_on:
      - mysqlproduction
      - mysqltest
  mysqlproduction:
    image: mysql:8.0.22
    restart: always
    container_name: mysqlproduction
    environment:
      MYSQL_DATABASE: 'final_quiz'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'finalquiz'
      MYSQL_ROOT_PASSWORD: 'finalquiz'
    ports:
      - '3333:3306'
    volumes:
      - $PWD/data:/var/lib/mysql-production
    command:
      --server_id=100
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci

  mysqltest:
    image: mysql:8.0.22
    container_name: mysqltest
    environment:
      MYSQL_DATABASE: 'final_quiz_test'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'finalquiz_test'
      MYSQL_ROOT_PASSWORD: 'finalquiz'
    ports:
      - '3334:3306'
    volumes:
      - $PWD/data:/var/lib/mysql-test
    command:
      --server_id=200
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci